name: Node CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy nextjs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: stoping PM2
        run: sudo pm2 stop 0
      - name: Git pull
        run: git pull
      - name: Install npm dependencies
        run: yarn install
      - name: Run build task
        run: yarn build
      - name: Start PM2
        run: sudo pm2 start 0
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }} 
