name: Node CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy nextjs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: SSH
        run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ubuntu@3.80.12.156
      - name: stoping PM2
        run: sudo pm2 stop 0
      - name: Git pull
        run: git pull
      - name: Install npm dependencies
        run: yarn install
      - name: Run build task
        run: yarn build
      - name: Start PM2
        run: sudo pm2 start 0
      - name: exit
        run: exit
